namespace pixelgun.tutorial
{
	public enum TUTORIAL_UI_IDS
	{
		MAIN_MENU_OPEN_SHOP_BUTTON = 0,
		SHOP_WINDOW_CLOSE_BUTTON = 1,
		MAIN_MENU_OPEN_LOBBY = 2,
		MAIN_MENU_OPEN_SELECT_MAP = 3,
		BATTLE_BUTTON = 4,
		STAR_RANDOM_BATTLE_BUTTON = 5
	}
}
