namespace engine.unity
{
	public enum GameWindowType
	{
		NotInit = 0,
		None = 1,
		CheatPanel = 2,
		ChooseMissions = 3,
		ChooseWorld = 4,
		LevelComplete = 5,
		LevelUp = 6,
		Loading = 7,
		Message = 8,
		PauseBattle = 9,
		RespawnBattle = 10,
		SelectMap = 11,
		Settings = 12,
		SettingsControl = 13,
		Shop = 14,
		BugReport = 15,
		ExitGameWindow = 16,
		MapList = 17,
		CreateBattle = 18,
		Profile = 19,
		BattleOver = 20,
		ArenaComplete = 21,
		Bank = 22,
		ConfirmBankWindow = 23,
		ClanWindow = 24,
		Stock = 25,
		ClanTopWindow = 26,
		ClanMessageWindow = 27,
		ClanCreateWindow = 28,
		MessageAnimateWindow = 29,
		BankCheckoutWindow = 30,
		RankTrophyChangeWindow = 31,
		RankSeasonCompleteWindow = 32,
		RebuyArticulWindow = 33,
		RankInfoWindow = 34,
		GachaWindow = 35,
		GachaRewardWindow = 36,
		RankCupChangeWindow = 37
	}
}
