public enum NotificationType
{
	NOTIFICATION_4LEVEL = 1,
	NOTIFICATION_CLAN_INVITE = 2,
	NOTIFICATION_CLAN_ENTER = 3,
	NOTIFICATION_CLAN_CLEANED = 4,
	NOTIFICATION_BANK_BUY = 5,
	NOTIFICATION_EMAIL_CONFIRM = 6,
	NOTIFICATION_MAINTANANCE = 7,
	NOTIFICATION_WARNING = 8,
	NOTIFICATION_FRIENDSP_REQ = 9,
	NOTIFICATION_HELP_REQ = 10,
	NOTIFICATION_CLAN_BATTLE_INVITE = 11,
	NOTIFICATION_CLAN_FRIENDLY_BATTLE_INVITE = 12,
	NOTIFICATION_RANK_SEASON_TIME_END = 13,
	NOTIFICATION_SETTINGS_CHANGED = 14
}
