public enum SlotType
{
	SLOT_NONE = 0,
	SLOT_WEAPON_PRIMARY = 1,
	SLOT_WEAPON_BACKUP = 2,
	SLOT_WEAPON_MELEE = 3,
	SLOT_WEAPON_SPECIAL = 4,
	SLOT_WEAPON_PREMIUM = 5,
	SLOT_WEAPON_SNIPER = 6,
	SLOT_WEAR_HAT = 7,
	SLOT_WEAR_ARMOR = 8,
	SLOT_WEAR_SKIN = 9,
	SLOT_WEAR_CAPE = 10,
	SLOT_WEAR_BOOTS = 11,
	SLOT_CONSUM_POTION = 12,
	SLOT_CONSUM_JETPACK = 13,
	SLOT_CONSUM_MECH = 14,
	SLOT_CONSUM_TURRET = 15,
	SLOT_CONSUM_GRENADE = 16,
	SLOT_RANK_CUP = 17
}
